"""
chains.py — LangChain LCEL Pipeline

This module is the heart of the application — it connects all the pieces
into a working pipeline using LangChain Expression Language (LCEL).

WHY LCEL (LangChain Expression Language)?
  LCEL uses Python's pipe operator (|) to compose Runnables.
  Every LangChain component (prompts, LLMs, parsers, retrievers) is a
  Runnable — an object with .invoke(), .stream(), and .batch() methods.

  The chain:
    prompt | llm | parser

  Reads left to right:
    1. prompt  → formats the input dict into a structured prompt
    2. llm     → sends the prompt to the model, gets raw output
    3. parser  → converts raw output to a clean Python string

  Benefits of LCEL:
    • Declarative — easy to read and understand
    • Composable — swap any component without touching others
    • Streaming-native — .stream() works on any LCEL chain automatically
    • RAG-ready — adding a retriever is just one more pipe stage

WHY STREAMING IN THE CHAIN?
  Without streaming: user waits 30–60 seconds for a complete response
  With streaming:    user sees the first token in ~1–2 seconds

  LCEL chains support streaming natively — calling chain.stream()
  instead of chain.invoke() automatically propagates the stream
  through every stage of the pipeline.

RAG READINESS NOTE (v0.3):
  To add RAG, you would modify get_chain() to accept a retriever and
  inject retrieved context into the prompt. The streaming and memory
  logic in stream_response() would NOT change at all.

  v0.3 chain would look like:
    from langchain_core.runnables import RunnablePassthrough
    chain = (
        {
            "context": retriever | format_docs,
            "history": RunnablePassthrough(),
            "input": RunnablePassthrough(),
        }
        | prompt
        | llm
        | parser
    )
"""

import logging
from typing import Generator, List, Optional

from langchain_community.llms import LlamaCpp
from langchain_core.messages import BaseMessage
from langchain_core.runnables import RunnableSerializable

from src.parsers import get_string_parser
from src.prompts import build_chatml_prompt, get_chat_prompt

logger = logging.getLogger(__name__)


def get_chain(
    llm: LlamaCpp,
    system_prompt: Optional[str] = None,
) -> RunnableSerializable:
    """
    Build and return the LCEL conversation chain.

    Pipeline: prompt | llm | parser

    Args:
        llm:           The loaded LlamaCpp model instance from llm.py
        system_prompt: Optional custom system prompt. Uses default if None.

    Returns:
        A RunnableSerializable — the composed LCEL chain.
        Supports .invoke(), .stream(), and .batch() out of the box.
    """
    prompt = get_chat_prompt(system_prompt=system_prompt or "")
    parser = get_string_parser()
    chain = prompt | llm | parser
    return chain


def stream_response(
    chain: RunnableSerializable,
    user_input: str,
    history: List[BaseMessage],
    system_prompt: Optional[str] = None,
) -> Generator[str, None, None]:
    """
    Stream the model's response token by token.

    Builds a TinyLlama ChatML-format prompt from history + user_input,
    then streams the result through the LCEL chain.

    Args:
        chain:         The LCEL chain from get_chain()
        user_input:    The user's current message
        history:       List of past messages (HumanMessage / AIMessage)
        system_prompt: Optional system prompt override

    Yields:
        str — each chunk/token as it's generated by the model
    """
    from src.config import DEFAULT_SYSTEM_PROMPT
    prompt_str = build_chatml_prompt(
        history=history,
        user_input=user_input,
        system_prompt=system_prompt or DEFAULT_SYSTEM_PROMPT,
    )

    logger.debug(f"Streaming response for input: {user_input[:50]}...")
    logger.debug(f"History turns in context: {len(history) // 2}")

    try:
        for chunk in chain.stream({"prompt": prompt_str}):
            if chunk:
                yield chunk
    except Exception as e:
        logger.error(f"Error during streaming: {e}")
        raise RuntimeError(
            f"An error occurred during response generation.\n"
            f"This may indicate insufficient RAM or a context overflow.\n"
            f"Try shortening your conversation or starting a new chat.\n"
            f"Technical detail: {str(e)}"
        )


def invoke_response(
    chain: RunnableSerializable,
    user_input: str,
    history: List[BaseMessage],
    system_prompt: Optional[str] = None,
) -> str:
    """
    Non-streaming version — returns the complete response as a single string.

    Args:
        chain:         The LCEL chain from get_chain()
        user_input:    The user's current message
        history:       List of past messages
        system_prompt: Optional system prompt override

    Returns:
        The complete response as a string
    """
    from src.config import DEFAULT_SYSTEM_PROMPT
    prompt_str = build_chatml_prompt(
        history=history,
        user_input=user_input,
        system_prompt=system_prompt or DEFAULT_SYSTEM_PROMPT,
    )
    return chain.invoke({"prompt": prompt_str})
